_base_ = ["Chinese.py"]

# Smoke-test config for the glyph-bank based ancient vertical synthetic data.
# This dataset is generated by tools/generate_vertical_ancient_synth.py and
# follows the same MTH-style labels.pkl + raw label_char layout.

num_classes = 6700

lr = 1e-4
lr_backbone = 1e-5
weight_decay = 1e-4
batch_size = 2

epochs = 2
lr_drop = 1
save_checkpoint_interval = 1
max_iterations = 5000

mode_chr = True

mth1000_root = "synth_vertical_ancient_smoke5k_dtlr"
mth1000_raw_root = "SynthVerticalAncientSmoke5k"
mth1000_labels_file = "labels.pkl"
mth1000_images_subdir = "lines"
mth1000_image_ext = "jpg"
mth1000_use_char_boxes = True

direction_source = "label"
forced_direction = "vertical"
mth1000_filter_direction = "vertical"

data_aug_scales = [768]
data_aug_max_size = 1600
